/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Excepciones.CampoVacio;
import javax.swing.JOptionPane;
import t8p4ej1.*;
/**
 *
 * @author PETO
 */
public class LogIn extends javax.swing.JFrame {
    boolean comprobarNombre = false;
    int loginFallidos = 0;

    /**
     * Creates new form LogIn
     */
    public LogIn() {
        initComponents();
        this.setSize(550,350);
        this.setResizable(false); 
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tfUsuario = new javax.swing.JTextField();
        bAceptar = new javax.swing.JButton();
        bSalir = new javax.swing.JButton();
        pfContraseña = new javax.swing.JPasswordField();
        lablelAunNoTienesUsuario = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        jLabel5.setText("jLabel5");

        jLabel8.setText("jLabel8");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(51, 0, 255));
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 36)); // NOI18N
        jLabel1.setText("Gestión de personal");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(70, 20, 410, 60);

        jLabel2.setText("Usuario");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(70, 114, 48, 16);

        jLabel3.setText("Contraseña");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(70, 201, 71, 16);

        jLabel7.setIcon(new javax.swing.ImageIcon("/Volumes/DAW /Programacion/Capitulo 8/PRACTICA 4/t8p4ej1/pass.png")); // NOI18N
        jPanel2.add(jLabel7);
        jLabel7.setBounds(400, 200, 20, 20);

        jLabel6.setIcon(new javax.swing.ImageIcon("/Volumes/DAW /Programacion/Capitulo 8/PRACTICA 4/t8p4ej1/user.png")); // NOI18N
        jPanel2.add(jLabel6);
        jLabel6.setBounds(400, 110, 20, 20);

        tfUsuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfUsuarioFocusLost(evt);
            }
        });
        jPanel2.add(tfUsuario);
        tfUsuario.setBounds(227, 105, 200, 30);

        bAceptar.setText("Aceptar");
        bAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAceptarActionPerformed(evt);
            }
        });
        jPanel2.add(bAceptar);
        bAceptar.setBounds(122, 274, 92, 29);

        bSalir.setText("Salir");
        bSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSalirActionPerformed(evt);
            }
        });
        jPanel2.add(bSalir);
        bSalir.setBounds(352, 274, 75, 29);

        pfContraseña.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                pfContraseñaFocusLost(evt);
            }
        });
        jPanel2.add(pfContraseña);
        pfContraseña.setBounds(227, 196, 200, 30);

        lablelAunNoTienesUsuario.setForeground(new java.awt.Color(255, 255, 255));
        lablelAunNoTienesUsuario.setText("¿Aún no tienes usuario?");
        lablelAunNoTienesUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lablelAunNoTienesUsuarioMouseClicked(evt);
            }
        });
        jPanel2.add(lablelAunNoTienesUsuario);
        lablelAunNoTienesUsuario.setBounds(340, 240, 170, 16);

        jLabel4.setIcon(new javax.swing.ImageIcon("/Volumes/DAW /Programacion/Capitulo 8/PRACTICA 4/t8p4ej1/fondo.jpg")); // NOI18N
        jPanel2.add(jLabel4);
        jLabel4.setBounds(0, 0, 700, 340);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 551, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSalirActionPerformed
        // Al pulsar el botón de "Salir" ...
        tfUsuario.setText(" ");
        pfContraseña.setText(" ");
        System.exit(0);
    }//GEN-LAST:event_bSalirActionPerformed

    private void tfUsuarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfUsuarioFocusLost
        // Comprobamos que el campo no esté vacío:
        
        /*try{
            if(tfUsuario.getText().isEmpty()){
            throw new CampoVacio();
            }
        }
        catch(CampoVacio e){
            JOptionPane.showMessageDialog(this,"El campo 'Usuario' no puede estar vacío");
            tfUsuario.requestFocus();
        }
        catch(Exception e){
            
        }*/
        
        
    }//GEN-LAST:event_tfUsuarioFocusLost

    private void pfContraseñaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pfContraseñaFocusLost
        // Comprobamos la contraseña
        /*try{
            if(pfContraseña.getText().isEmpty()){
            throw new CampoVacio();
            }
        }
        catch(CampoVacio e){
            JOptionPane.showMessageDialog(this,"El campo 'Contraseña' no puede estar vacío");
            pfContraseña.requestFocus();
        }
        catch(Exception e){
            
        }*/
    }//GEN-LAST:event_pfContraseñaFocusLost

    private void bAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAceptarActionPerformed
        // Comprobamos que el campo no esté vacío:
        
        
        //SI ES VALIDO. PARA MI SIEMPRE ES, PERO NOUP
        
        String nombre = tfUsuario.getText();
        //String contraseña = pfContraseña.toString();
        
        String pwd = new String(pfContraseña.getPassword());
        
        if(!t8p4ej1.Main.comprobarLogin(nombre, pwd)){
            
            System.out.println("NO VALIDO");
            
            loginFallidos++;
            JOptionPane.showMessageDialog(null,"Llevas " + loginFallidos + " fallo(s)");
        }else{
            
            System.out.println("VALIDO");
            
            t8p4ej1.Main.finalizarLogin();
        }
       
        
        if(loginFallidos == 3){
            JOptionPane.showMessageDialog(null, "Demasiados errores, aguuuuur");
            System.exit(0);       
        }
        
        
        
        //t8p4ej1.Main.finalizarLogin();
        
    }//GEN-LAST:event_bAceptarActionPerformed

    private void lablelAunNoTienesUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lablelAunNoTienesUsuarioMouseClicked
        // ¿Aún no tienes usuario?
        Main.crearUsuarioNuevoVentana();
    }//GEN-LAST:event_lablelAunNoTienesUsuarioMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LogIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAceptar;
    private javax.swing.JButton bSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lablelAunNoTienesUsuario;
    private javax.swing.JPasswordField pfContraseña;
    private javax.swing.JTextField tfUsuario;
    // End of variables declaration//GEN-END:variables
}
